### PR TITLE
Use Lwt to manage processes

### LINKED ISSUE #6: Spurious fuzzer termination message
During `bun` runs, it appears that immediately after `bun` prints the stats message, it observes termination of all fuzzers. But I can see in `top` that all fuzzing jobs are still running. The relevant part of the output is produced below:

```
.....
>>> 9 (0 days, 0 hrs) <<<                       
                                                           
  cycle 1, lifetime speed 1 execs/sec, path 0/1 (0%)        
  pending 1/1, coverage 0.28%, no crashes yet                              
                                                           
Summary stats                                
=============                                               
                                                                                                                       
       Fuzzers alive : 32       
      Total run time : 0 days, 0 hours                           
         Total execs : 0 million                                
    Cumulative speed : 32 execs/sec                         
       Pending paths : 32 faves, 32 total                                  
  Pending per fuzzer : 1 faves, 1 total (on average)                                                                   
       Crashes found : 0 locally unique                          
                                                           
All fuzzers have terminated.                                          
All fuzzers have terminated.                               
All fuzzers have terminated.                                
All fuzzers have terminated.               
...
```

Is this a known behaviour? I am using bun.0.3.2, afl-fuzz 2.52b, crowbar.0.1. 

I will try to reproduce this in a container.

### PR DESCRIPTION
**Pull request by talex5**
Hopefully fixes #6. I also migrated to Dune, switched to `Logs` for logging to simplify the code, and added timestamps. Only lightly tested so far...

### CODE REVIEW

**Comment by yomimono** [comment]
Thanks for this! I have no trouble believing that these changes are an improvement. Would you like to be added as an author? It's a pretty substantial rewrite.

**Comment by talex5** [comment]
OK, added! Does it work for you?

**Comment by talex5** [comment]
Hmm, bun's Travis CI is failing because `test/short.ml` has a bug that the fuzzer finds. Is that supposed to happen?

```
$ _build/default/test/short.exe  crash_1.1555608100 
negation: ....
negation: FAIL

When given the input:

    0.000000
    
the test failed:

    check false
    
Fatal error: exception Crowbar.TestFailure
```

**Comment by yomimono** [comment]
It looks like previously [AFL detected a crash but we didn't report it](https://travis-ci.org/yomimono/ocaml-bun/jobs/373662693#L9187) which is definitely wrong :roll_eyes:

**Pull request merged**
